version: "3.9"

###############################################################################
# configure the project services
services:

  #############################################################################
  # configure the Go backend container
  backend-dev:
    build: 
      context: backend/
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    restart: unless-stopped
    volumes:
      - ./backend:/app
    ports:
      - "4001:4000"
    links:
      - db-dev
    networks:
      - api-interface

  #############################################################################
  # configure the Angular frontend
  frontend-dev:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    links:
      - backend-dev
    environment:
      - BACKEND_URL=http://localhost:4001
    networks:
      - api-interface

  #############################################################################
  # configure the MySQL container
  db-dev:
    build: db/
    container_name: db-dev
    ports:
      - "3200:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: backend
      MYSQL_PASSWORD_FILE: /run/secrets/db_pw
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pw
    secrets:
      - db_pw
      - db_root_pw

###############################################################################
# configure the project secrets
secrets:
  db_pw:
    file: ./secrets/db_pw
  db_root_pw:
    file: ./secrets/db_root_pw

###############################################################################
# configure the project networks
networks:
  api-interface:
    driver: bridge
