version: "3.9"

###############################################################################
# configure the project services
services:

  #############################################################################
  # configure the Go backend container
  backend:
    build: backend/
    container_name: backend-dev
    restart: unless-stopped
    ports:
      - "4001:4000"
    links:
      - db

  #############################################################################
  # configure the Angular frontend
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    links:
      - backend

  #############################################################################
  # configure the MySQL container
  db:
    image: mysql:8
    container_name: db-dev
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3200:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: backend
      MYSQL_PASSWORD_FILE: /run/secrets/db_pw
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_pw
    secrets:
      - db_pw
      - db_root_pw

###############################################################################
# configure the project secrets
secrets:
  db_pw:
    file: ./secrets/db_pw
  db_root_pw:
    file: ./secrets/db_root_pw
